codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "40...80"  # Ajustado para nosso projeto atual (50% cobertura)
  status:
    project:
      default:
        target: 50%  # Meta realista baseada na cobertura atual
        threshold: 5%
    patch:
      default:
        target: 60%  # Um pouco mais alto para novos códigos
        threshold: 10%

# Comment configuration for pull requests
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

# Ignore certain files from coverage
ignore:
  - "tests/"
  - "**/__pycache__/**"
  - "*.pyc"
  - "conftest.py"
  - "app/main.py"  # Arquivo principal de execução

# Flag configuration
flags:
  unittests:
    paths:
      - app/src/
    carryforward: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no 
