#version: '3.8'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.db
    container_name: 2025_1_Minecraft
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 2025_1_Minecraft
    ports:
      - "5433:5432"
    volumes:
      # Estrutura organizada e faseada
      - ./db/init/01_users/create_users.sql:/docker-entrypoint-initdb.d/01_create_users.sql
      - ./db/init/02_schema/01_drop_tables.sql:/docker-entrypoint-initdb.d/02_drop_tables.sql
      - ./db/init/02_schema/02_base_tables.sql:/docker-entrypoint-initdb.d/03_base_tables.sql
      - ./db/init/02_schema/03_dependent_tables.sql:/docker-entrypoint-initdb.d/04_dependent_tables.sql
      - ./db/init/02_schema/03_5_aldeao_table.sql:/docker-entrypoint-initdb.d/04_5_aldeao_table.sql
      - ./db/init/02_schema/04_relationship_tables.sql:/docker-entrypoint-initdb.d/05_relationship_tables.sql
      - ./db/init/02_schema/05_game_tables.sql:/docker-entrypoint-initdb.d/06_game_tables.sql
      - ./db/init/02_schema/06_indexes.sql:/docker-entrypoint-initdb.d/07_indexes.sql
      - ./db/init/03_data/01_basic_data.sql:/docker-entrypoint-initdb.d/08_basic_data.sql
      - ./db/init/03_data/02_chunks.sql:/docker-entrypoint-initdb.d/09_chunks.sql
      - ./db/init/03_data/03_players.sql:/docker-entrypoint-initdb.d/10_players.sql
      - ./db/init/03_data/03_5_aldeao_data.sql:/docker-entrypoint-initdb.d/10_5_aldeao_data.sql
      - ./db/init/03_data/04_inventory.sql:/docker-entrypoint-initdb.d/11_inventory.sql
      - ./db/init/03_data/05_game_data.sql:/docker-entrypoint-initdb.d/12_game_data.sql
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    container_name: python_mine
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/2025_1_Minecraft
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./db:/app/db
    # command: >
    #   sh -c './wait-for-it.sh db:5432 -- python main.py'

volumes:
  db_data:
