site_name: Minecraft
theme:
  #name: dracula
  name: material
nav:
  - Início: inicio.md
  - Módulo 1:
      - Diagrama Entidade-Relacionamento: der.md
      - Modelo Relacional: modeloRelacional.md
      - Dicionário de Dados: dicionario.md
  - Entregas:
      - Modulo 1: modulo1.md
