FROM postgres:16-bullseye

RUN apt-get update && apt-get install -y postgresql-16-cron

RUN echo "shared_preload_libraries='pg_cron'" >> /usr/share/postgresql/postgresql.conf.sample
RUN echo "cron.database_name='2025_1_Minecraft'" >> /usr/share/postgresql/postgresql.conf.sample