name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and test with Docker Compose
      run: |
        # Try docker compose first, fallback to docker-compose
        if command -v docker compose &> /dev/null; then
          echo "Using docker compose"
          docker compose build
          docker compose up -d
          sleep 15
          docker compose exec -T app python -m pytest tests/ -v --tb=short
        else
          echo "Using docker-compose"
          docker-compose build
          docker-compose up -d db
          sleep 15
          docker-compose exec -T app python -m pytest tests/ -v --tb=short
        fi
        
    - name: Run tests with coverage
      run: |
        # Try docker compose first, fallback to docker-compose
        if command -v docker compose &> /dev/null; then
          docker compose exec -T app python -m pytest tests/ --cov=src --cov-report=xml --cov-report=term-missing
        else
          docker-compose exec -T app python -m pytest tests/ --cov=src --cov-report=xml --cov-report=term-missing
        fi
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./app/coverage.xml
        flags: unittests
        name: codecov-umbrella
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          app/.pytest_cache/
          app/htmlcov/
        retention-days: 30 
